### ISSUE TITLE
NoClassDefFound: VPackModule (Java Driver)

### ISSUE THREAD

**Issue by darkfrog26** [arangodb/jackson-dataformat-velocypack#18]
## My Environment

* __ArangoDB Version__:        3.10.1
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               N/A
* __Infrastructure__:               local
* __Operating System__:        MacOS 13.1
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD

## Component, Query & Data

Using arangodb-java-driver 6.20.0, jackson-dataformat-velocypack 3.1.0, and velocypack 3.0.0, but I'm getting: `Uncaught exception when running spec.ArangoDBSpec: java.lang.NoClassDefFoundError: com/arangodb/velocypack/VPackModule` as a runtime exception when I try to connect to the database.

**Comment by rashtao** [comment]
To avoid compatibility problems of transitive dependencies, I set the dependency on `com.arangodb:velocypack` as `provided` and released it in https://github.com/arangodb/jackson-dataformat-velocypack/releases/tag/v4.0.0.
