### ISSUE TITLE
Translate or document needed annotations

### ISSUE THREAD

**Issue by rocketraman** [arangodb/jackson-dataformat-velocypack#3]
The VelocyJack serializer generally seems to work well, but it does not handle `@DocumentField`, `@SerializedName`, `@Expose`, etc., annotations.

While I understand these annotations are for the built-in serializer, the VelocyJack serializer should probably either a) handle these annotations, mapping them to the appropriate Jackson annotations, or b) document the fact that the annotations used must come from Jackson.

I actually think a combination of the above would be appropriate: specifically handle `@DocumentField` as serialization/deserialization of these fields is ArangoDB specific, and simple document the others. Their serialization is not specific to Arango VPack and it would not be unexpected for a Jackson user to use the appropriate Jackson equivalents.

**Comment by mpv1989** [comment]
Hi @rocketraman,

thanks for your feedback.

This project was requested from some people of our community which already use Jackson and do not want to use ArangoDBs sepcific annotations like `@DocumentField`. So we first implemented the basic usage of Jackson.

We are currently discussing if we want to replace the driver internal VelocyPack serializer with Jackson. Then we will for sure handle `@DocumentField` and other annotations and also custom serializers (`VPackSerializer` and `VPackDeserializer`).

**Comment by lamplis** [comment]
Using Jackson would really boost arrangodb integration in modern java projects !
VelocyJack may be more performant but maintenance in time and interoperability are now critical success factors.
We had to redevelop VelocityJack to use proper geojson with Jackson's anotations and it has been a pain.
This topic has been created in 2018, Keep us informed if you may prioritize it

**Comment by rashtao** [comment]
Support to `@DocumentField`, `@SerializedName` and `@Expose` has been added in github.com/arangodb/jackson-dataformat-velocypack/pull/13
